apiVersion: batch.tutorial.kubebuilder.io/v1
kind: CronJob
metadata:
  name: {{.ObjectMeta.Name}}
  namespace: {{.ObjectMeta.Namespace}}
spec:
  schedule: "1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: test-container
              image: test-image